add sql script for backup reasons
DeNic0la/M151-Movie-Database pull request #2
Opened 2022-05-25 09:22 UTC by Laurin-dev

2022-05-25 19:07 UTC, fabianmueller7 requested changes
Have a look at the comments please.

2022-05-25 19:07 UTC, fabianmueller7 commented on Movie-Db-CSS.sql
> +  `year` varchar(45) DEFAULT NULL,
Date?

2022-05-25 19:07 UTC, fabianmueller7 commented on Movie-Db-CSS.sql
> +  `title` varchar(45) DEFAULT NULL,
There are some realy long movie names, but thats okay.

2022-05-26 09:15 UTC, DeNic0la commented
There is a Better, Simpler SQL script already added. I Dont see the Value in this

2022-05-26 09:15 UTC, closed without merging